-- 사용자 계정 생성
CREATE USER C##KH IDENTIFIED BY 1234;

-- 권한부여
GRANT RESOURCE, CONNECT TO C##KH;

-- 테이블 스페이스 (ORA-01950)
ALTER USER C##KH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


-- PRACTICE 계정 생성
CREATE USER C##KH__PRACTICE IDENTIFIED BY 1234;

-- GRANT  권한, 권한2, ... TO 계정명;


GRANT RESOURCE, CONNECT TO C##KH__PRACTICE;

ALTER USER C##KH__PRACTICE DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;