-- 연습용

-- MEMBER 테이블 생성 (ID,PWD,NICK 3개 칼럼)
CREATE TABLE MEMBER(ID VARCHAR2(100), PWD VARCHAR2(100) , NICK VARCHAR2(100));
--ID,PWD,NICK 칼럼을 만듦, 타입은 가변문자열, 최대 100바이트

-- 데이터 생성(CREATE) INSERT
INSERT INTO MEMBER(ID, PWD, NICK) VALUES('USER01', '1234', 'NICK01');
INSERT INTO MEMBER(ID, PWD, NICK) VALUES('USER02', '2222', 'NICK02');
INSERT INTO MEMBER(ID, PWD, NICK) VALUES('USER03', '3333', 'NICK03');

-- 데이터 읽기(READ)
SELECT ID,PWD,NICK FROM MEMBER;
SELECT * FROM MEMBER;
SELECT ID FROM MEMBER;
SELECT PWD FROM MEMBER;
SELECT NICK FROM MEMBER;
SELECT ID,PWD FROM MEMBER;
SELECT ID, NICK FROM MEMBER;
SELECT PWD, NICK FROM MEMBER;


-- 데이터 수정(UPDATE)
UPDATE MEMBER SET PWD = '9999' WHERE ID = '';

-- 데이터 삭제(DELETE)
DELETE MEMBER WHERE ID = 'USER03';
DELETE MEMBER;

-- 테이블 삭제
DROP TABLE MEMBER;



-----------------------------------------------------------------------


-- 테이블 생성
CREATE TABLE HELLO(ID VARCHAR2(100), PWD VARCHAR2(100));

-- 데이터 넣기
INSERT INTO HELLO(ID,PWD) VALUES('USER01', '1234');

-- 데이터 조회
SELECT * FROM HELLO;
SELECT ID FROM HELLO;
SELECT PWD FROM HELLO;
SELECT ID,PWD FROM HELLO;

-- 데이터 수정
UPDATE HELLO SET PWD = '9999' WHERE ID = 'USER01';

-- 데이터 삭제
DELETE HELLO WHERE ID = 'USER01';

-- 테이블 삭제
DROP TABLE HELLO;




